os:
  - linux
  - windows
language: node_js
node_js:
  - '14'
  - '12'
  - '10'
after_success: npm run coverage

jobs:
  include:
    - if: branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/
      stage: npm release
      node_js: '14'
      script: echo "deploying to npm ..."
      after_success: echo "after script skipped ..."
      deploy:
        edge: true
        provider: npm
        on:
          tags: true
