name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm run test:lint
      - run: npm run test
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  test-dist:
    needs: test-src
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        node-version:
          - 10
          - 12
          - 14
    name: test-dist-${{ matrix.os }}-node-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test:dist

  test-all-success:
    needs:
      - test-src
      - test-dist
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
